# Generated by Django 3.2 on 2021-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=30, unique=True)),
                ('name', models.TextField(max_length=1000)),
                ('author', models.TextField(max_length=1000)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
